<?php

namespace ZesharCRM\Bundle\GoalsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ZesharCRM\Bundle\GoalsBundle\Entity\Goal;
use ZesharCRM\Bundle\GoalsBundle\Entity\GoalAssignment;
use ZesharCRM\Bundle\CoreBundle\Enum\GoalStatus;
/**
 * GoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalRepository extends EntityRepository
{
    public function createGoalAssignment(Goal $goal, $assignPerson, $count)
    {
        $em = $this->getEntityManager();
        $estimated = ($goal->getTotal()/$count+$goal->getTotal()/100*$goal->getEstimated())/count($assignPerson);

        foreach ($assignPerson as $user) {
            $goalAssignment = new GoalAssignment();
            $goalAssignment->setGoal($goal);
            $goalAssignment->setCurrent(0);
            $goalAssignment->setEstimated($estimated);
            $goalAssignment->setStatus(GoalStatus::OPEN);
            $goalAssignment->setAssignee($user);
            $em->persist($goalAssignment);
            $em->flush($goalAssignment);
            unset($goalAssignment);
        }
    }


}
