<?php

namespace ZesharCRM\Bundle\LeadScoringBundle\Repository;

use ZesharCRM\Bundle\CoreBundle\Entity\Lead;
use ZesharCRM\Bundle\LeadScoringBundle\Entity\LeadScoring;
use Doctrine\ORM\EntityRepository;
use ZesharCRM\Bundle\CoreBundle\Entity\Opportunity;

/**
 * LeadScoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadScoringRepository extends EntityRepository
{
    
    public function getLeadScoringByLead(/*Lead*/ $lead)
    {
        if($lead instanceof Opportunity){
            $lead = $lead->getLead();
        }
        $entity = $this->findOneBy(array('lead' => $lead->getId()));
        if(!$entity){
            $entity = new LeadScoring();
            $entity->setLead($lead);
            $this->_em->persist($entity);
        }
        return $entity;
    }

    public function attachPortions($entities, $portion = null){
        if(!is_array($entities)){
            $entities = $entities->toArray();
        }
        $totalSet = array_map(function($entity){
              return $entity->getScore();
          }, $entities);
        $totalAmount = array_sum($totalSet);
        foreach($entities as $entity){
            if ($portion) {
              $currentPercent = ($portion * ($entity->getScore() / $totalAmount));
            } else {
              $currentPercent = ($entity->getScore() / $totalAmount);
            }
            if (count($entity->getChildren()) > 0){
              $this->attachPortions($entity->getChildren(), $currentPercent);
            } else {
              $entity->portionScore = $currentPercent;
            }
        }
    }
    
}
