<?php

namespace Proxies\__CG__\ZesharCRM\Bundle\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lead extends \ZesharCRM\Bundle\CoreBundle\Entity\Lead implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\Lead' . "\0" . 'type', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\Lead' . "\0" . 'creator', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\Lead' . "\0" . 'assignee', 'name', 'scoring', 'leadType', 'systemLeadType', 'status', 'isArchive', 'deletedAt', 'createdAt', 'updatedAt', 'newAttachment', 'newAttachmentFile', 'prequalificationAutos', 'prequalificationDrivers', 'prequalificationInsuredAddresses', 'previousCarrierXDate', 'previousCarrierPolice', 'previousCarrierName', 'operations', 'milestoneOperations', 'contactCardOpportunity', 'contactCard', 'opportunity', 'leadCategory', 'purchasedAt', 'purchaseAmount', 'estimatedValue', 'attachments', 'leadCampaign', 'leadSource', 'leadEvents');
        }

        return array('__isInitialized__', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\Lead' . "\0" . 'type', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\Lead' . "\0" . 'creator', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\Lead' . "\0" . 'assignee', 'name', 'scoring', 'leadType', 'systemLeadType', 'status', 'isArchive', 'deletedAt', 'createdAt', 'updatedAt', 'newAttachment', 'newAttachmentFile', 'prequalificationAutos', 'prequalificationDrivers', 'prequalificationInsuredAddresses', 'previousCarrierXDate', 'previousCarrierPolice', 'previousCarrierName', 'operations', 'milestoneOperations', 'contactCardOpportunity', 'contactCard', 'opportunity', 'leadCategory', 'purchasedAt', 'purchaseAmount', 'estimatedValue', 'attachments', 'leadCampaign', 'leadSource', 'leadEvents');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lead $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\ZesharCRM\Bundle\CoreBundle\Entity\User $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssignee(\ZesharCRM\Bundle\CoreBundle\Entity\User $assignee = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssignee', array($assignee));

        return parent::setAssignee($assignee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignee', array());

        return parent::getAssignee();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactCardOpportunity($contactCardOpportunity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactCardOpportunity', array($contactCardOpportunity));

        return parent::setContactCardOpportunity($contactCardOpportunity);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactCardOpportunity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactCardOpportunity', array());

        return parent::getContactCardOpportunity();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantity($quantity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantity', array($quantity));

        return parent::setQuantity($quantity);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantity', array());

        return parent::getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsArchive($isArchive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsArchive', array($isArchive));

        return parent::setIsArchive($isArchive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsArchive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsArchive', array());

        return parent::getIsArchive();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeadType($leadType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeadType', array($leadType));

        return parent::setLeadType($leadType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', array());

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deletedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', array($deletedAt));

        return parent::setDeletedAt($deletedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadType', array());

        return parent::getLeadType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSystemLeadType($systemLeadType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSystemLeadType', array($systemLeadType));

        return parent::setSystemLeadType($systemLeadType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSystemLeadType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSystemLeadType', array());

        return parent::getSystemLeadType();
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousCarrierPolice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousCarrierPolice', array());

        return parent::getPreviousCarrierPolice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousCarrierPolice($previousCarrierPolice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousCarrierPolice', array($previousCarrierPolice));

        return parent::setPreviousCarrierPolice($previousCarrierPolice);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousCarrierXDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousCarrierXDate', array());

        return parent::getPreviousCarrierXDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousCarrierXDate($previousCarrierXDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousCarrierXDate', array($previousCarrierXDate));

        return parent::setPreviousCarrierXDate($previousCarrierXDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousCarrierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousCarrierName', array());

        return parent::getPreviousCarrierName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousCarierName($previousCarrierName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousCarierName', array($previousCarrierName));

        return parent::setPreviousCarierName($previousCarrierName);
    }

    /**
     * {@inheritDoc}
     */
    public function addPrequalificationInsuredAddress($prequalificationInsuredAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrequalificationInsuredAddress', array($prequalificationInsuredAddress));

        return parent::addPrequalificationInsuredAddress($prequalificationInsuredAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrequalificationInsuredAddresses($prequalificationInsuredAddresses)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrequalificationInsuredAddresses', array($prequalificationInsuredAddresses));

        return parent::setPrequalificationInsuredAddresses($prequalificationInsuredAddresses);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrequalificationInsuredAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrequalificationInsuredAddresses', array());

        return parent::getPrequalificationInsuredAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function removePrequalificationInsuredAddress(\ZesharCRM\Bundle\CoreBundle\Entity\LeadPrequalificationInsuredAddress $prequalificationInsuredAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrequalificationInsuredAddress', array($prequalificationInsuredAddress));

        return parent::removePrequalificationInsuredAddress($prequalificationInsuredAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function addPrequalificationDriver($prequalificationDriver)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrequalificationDriver', array($prequalificationDriver));

        return parent::addPrequalificationDriver($prequalificationDriver);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrequalificationDrivers($prequalificationDrivers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrequalificationDrivers', array($prequalificationDrivers));

        return parent::setPrequalificationDrivers($prequalificationDrivers);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrequalificationDrivers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrequalificationDrivers', array());

        return parent::getPrequalificationDrivers();
    }

    /**
     * {@inheritDoc}
     */
    public function removePrequalificationDriver(\ZesharCRM\Bundle\CoreBundle\Entity\LeadPrequalificationDriver $prequalificationDriver)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrequalificationDriver', array($prequalificationDriver));

        return parent::removePrequalificationDriver($prequalificationDriver);
    }

    /**
     * {@inheritDoc}
     */
    public function addPrequalificationAuto($prequalificationAuto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrequalificationAuto', array($prequalificationAuto));

        return parent::addPrequalificationAuto($prequalificationAuto);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrequalificationAutos($prequalificationAutos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrequalificationAutos', array($prequalificationAutos));

        return parent::setPrequalificationAutos($prequalificationAutos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrequalificationAutos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrequalificationAutos', array());

        return parent::getPrequalificationAutos();
    }

    /**
     * {@inheritDoc}
     */
    public function removePrequalificationAuto(\ZesharCRM\Bundle\CoreBundle\Entity\LeadPrequalificationAuto $prequalificationAuto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrequalificationAuto', array($prequalificationAuto));

        return parent::removePrequalificationAuto($prequalificationAuto);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactCard(\ZesharCRM\Bundle\CoreBundle\Entity\ContactCard $contactCard = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactCard', array($contactCard));

        return parent::setContactCard($contactCard);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactCard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactCard', array());

        return parent::getContactCard();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpportunity(\ZesharCRM\Bundle\CoreBundle\Entity\Opportunity $opportunity = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpportunity', array($opportunity));

        return parent::setOpportunity($opportunity);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpportunity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpportunity', array());

        return parent::getOpportunity();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeString', array());

        return parent::getTypeString();
    }

    /**
     * {@inheritDoc}
     */
    public function getSystemTypeString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSystemTypeString', array());

        return parent::getSystemTypeString();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusString', array());

        return parent::getStatusString();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeadCategory(\ZesharCRM\Bundle\CoreBundle\Entity\LeadCategory $leadCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeadCategory', array($leadCategory));

        return parent::setLeadCategory($leadCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadCategory', array());

        return parent::getLeadCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchasedAt($purchasedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchasedAt', array($purchasedAt));

        return parent::setPurchasedAt($purchasedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchasedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchasedAt', array());

        return parent::getPurchasedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchaseAmount($purchaseAmount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchaseAmount', array($purchaseAmount));

        return parent::setPurchaseAmount($purchaseAmount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchaseAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchaseAmount', array());

        return parent::getPurchaseAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstimatedValue($estimatedValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstimatedValue', array($estimatedValue));

        return parent::setEstimatedValue($estimatedValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstimatedValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstimatedValue', array());

        return parent::getEstimatedValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', array());

        return parent::getAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewAttachment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewAttachment', array());

        return parent::getNewAttachment();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewAttachment($newAttachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewAttachment', array($newAttachment));

        return parent::setNewAttachment($newAttachment);
    }

    /**
     * {@inheritDoc}
     */
    public function getNewAttachmentFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewAttachmentFile', array());

        return parent::getNewAttachmentFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setNewAttachmentFile($newAttachmentFile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNewAttachmentFile', array($newAttachmentFile));

        return parent::setNewAttachmentFile($newAttachmentFile);
    }

    /**
     * {@inheritDoc}
     */
    public function setAttachments($attachments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAttachments', array($attachments));

        return parent::setAttachments($attachments);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadCampaign()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadCampaign', array());

        return parent::getLeadCampaign();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeadCampaign($leadCampaign)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeadCampaign', array($leadCampaign));

        return parent::setLeadCampaign($leadCampaign);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadSource()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadSource', array());

        return parent::getLeadSource();
    }

    /**
     * {@inheritDoc}
     */
    public function setLeadSource($leadSource)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeadSource', array($leadSource));

        return parent::setLeadSource($leadSource);
    }

    /**
     * {@inheritDoc}
     */
    public function addLeadEvent(\ZesharCRM\Bundle\CoreBundle\Entity\LeadEvent $leadEvents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLeadEvent', array($leadEvents));

        return parent::addLeadEvent($leadEvents);
    }

    /**
     * {@inheritDoc}
     */
    public function setLeadEvents($leadEvents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLeadEvents', array($leadEvents));

        return parent::setLeadEvents($leadEvents);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLeadEvent(\ZesharCRM\Bundle\CoreBundle\Entity\LeadEvent $leadEvents)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLeadEvent', array($leadEvents));

        return parent::removeLeadEvent($leadEvents);
    }

    /**
     * {@inheritDoc}
     */
    public function getLeadEvents()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLeadEvents', array());

        return parent::getLeadEvents();
    }

    /**
     * {@inheritDoc}
     */
    public function addOperation($operation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOperation', array($operation));

        return parent::addOperation($operation);
    }

    /**
     * {@inheritDoc}
     */
    public function addMilestoneOperation(\ZesharCRM\Bundle\CoreBundle\Entity\MilestoneOperation $milestoneOperation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMilestoneOperation', array($milestoneOperation));

        return parent::addMilestoneOperation($milestoneOperation);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperations', array());

        return parent::getOperations();
    }

    /**
     * {@inheritDoc}
     */
    public function getMilestoneOperations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMilestoneOperations', array());

        return parent::getMilestoneOperations();
    }

    /**
     * {@inheritDoc}
     */
    public function removeOperation(\ZesharCRM\Bundle\CoreBundle\Entity\Operation $operation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOperation', array($operation));

        return parent::removeOperation($operation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMilestoneOperation(\ZesharCRM\Bundle\CoreBundle\Entity\MilestoneOperation $milestoneOperation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMilestoneOperation', array($milestoneOperation));

        return parent::removeMilestoneOperation($milestoneOperation);
    }

    /**
     * {@inheritDoc}
     */
    public function getScoring()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getScoring', array());

        return parent::getScoring();
    }

    /**
     * {@inheritDoc}
     */
    public function setScoring($scoring)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setScoring', array($scoring));

        return parent::setScoring($scoring);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateField()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateField', array());

        return parent::getDateField();
    }

    /**
     * {@inheritDoc}
     */
    public function addCallReports(\ZesharCRM\Bundle\CallsBundle\Entity\CallReporting $callReports)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCallReports', array($callReports));

        return parent::addCallReports($callReports);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCallReports(\ZesharCRM\Bundle\CallsBundle\Entity\CallReporting $callReports)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCallReports', array($callReports));

        return parent::removeCallReports($callReports);
    }

    /**
     * {@inheritDoc}
     */
    public function getCallReport()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCallReport', array());

        return parent::getCallReport();
    }

}
