<?php

namespace Proxies\__CG__\ZesharCRM\Bundle\CallsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CallReporting extends \ZesharCRM\Bundle\CallsBundle\Entity\CallReporting implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'id', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'startsAt', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'status', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'type', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'assignee', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'contact', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'eventsType', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'lead', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'description', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'duration');
        }

        return array('__isInitialized__', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'id', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'startsAt', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'status', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'type', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'assignee', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'contact', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'eventsType', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'lead', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'description', '' . "\0" . 'ZesharCRM\\Bundle\\CallsBundle\\Entity\\CallReporting' . "\0" . 'duration');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CallReporting $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartsAt($startsAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartsAt', array($startsAt));

        return parent::setStartsAt($startsAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartsAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartsAt', array());

        return parent::getStartsAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setContact(\ZesharCRM\Bundle\CoreBundle\Entity\Contact $contact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContact', array($contact));

        return parent::setContact($contact);
    }

    /**
     * {@inheritDoc}
     */
    public function getContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContact', array());

        return parent::getContact();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeString', array());

        return parent::getTypeString();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusString', array());

        return parent::getStatusString();
    }

    /**
     * {@inheritDoc}
     */
    public function getEventsTypeString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventsTypeString', array());

        return parent::getEventsTypeString();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration($duration)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', array($duration));

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', array());

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssignee($assignee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssignee', array($assignee));

        return parent::setAssignee($assignee);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignee', array());

        return parent::getAssignee();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventsType($eventsType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventsType', array($eventsType));

        return parent::setEventsType($eventsType);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventsType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventsType', array());

        return parent::getEventsType();
    }

    /**
     * {@inheritDoc}
     */
    public function setLead($lead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLead', array($lead));

        return parent::setLead($lead);
    }

    /**
     * {@inheritDoc}
     */
    public function getLead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLead', array());

        return parent::getLead();
    }

}
