<?php

namespace Proxies\__CG__\ZesharCRM\Bundle\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LeadPrequalificationInsuredAddress extends \ZesharCRM\Bundle\CoreBundle\Entity\LeadPrequalificationInsuredAddress implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'id', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'address', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'state', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'zipCode', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'type', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'city', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'previousCarrierName', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'previousCarrierPolice', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'lead', 'previousCarrierXDate');
        }

        return array('__isInitialized__', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'id', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'address', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'state', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'zipCode', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'type', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'city', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'previousCarrierName', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'previousCarrierPolice', '' . "\0" . 'ZesharCRM\\Bundle\\CoreBundle\\Entity\\LeadPrequalificationInsuredAddress' . "\0" . 'lead', 'previousCarrierXDate');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LeadPrequalificationInsuredAddress $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousCarrierXDate($previousCarrierXDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousCarrierXDate', array($previousCarrierXDate));

        return parent::setPreviousCarrierXDate($previousCarrierXDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousCarrierXDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousCarrierXDate', array());

        return parent::getPreviousCarrierXDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLead($lead)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLead', array($lead));

        return parent::setLead($lead);
    }

    /**
     * {@inheritDoc}
     */
    public function getLead()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLead', array());

        return parent::getLead();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousCarrierPolice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousCarrierPolice', array());

        return parent::getPreviousCarrierPolice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousCarrierPolice($previousCarrierPolice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousCarrierPolice', array($previousCarrierPolice));

        return parent::setPreviousCarrierPolice($previousCarrierPolice);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreviousCarrierName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreviousCarrierName', array());

        return parent::getPreviousCarrierName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreviousCarrierName($previousCarrierName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreviousCarrierName', array($previousCarrierName));

        return parent::setPreviousCarrierName($previousCarrierName);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setState($state)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setState', array($state));

        return parent::setState($state);
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', array());

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipCode($zipCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipCode', array($zipCode));

        return parent::setZipCode($zipCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipCode', array());

        return parent::getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeString', array());

        return parent::getTypeString();
    }

}
