<?php

namespace Proxies\__CG__\ZesharCRM\Bundle\GoalsBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Goal extends \ZesharCRM\Bundle\GoalsBundle\Entity\Goal implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'id', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'description', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'creator', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'estimated', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'title', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'assignments', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'goalCategory', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'total', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'startsAt', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'finishesAt');
        }

        return array('__isInitialized__', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'id', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'description', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'creator', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'estimated', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'title', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'assignments', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'goalCategory', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'total', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'startsAt', '' . "\0" . 'ZesharCRM\\Bundle\\GoalsBundle\\Entity\\Goal' . "\0" . 'finishesAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Goal $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator($creator)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstimated($estimated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstimated', array($estimated));

        return parent::setEstimated($estimated);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstimated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstimated', array());

        return parent::getEstimated();
    }

    /**
     * {@inheritDoc}
     */
    public function addAssignment(\ZesharCRM\Bundle\GoalsBundle\Entity\GoalAssignment $assignments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAssignment', array($assignments));

        return parent::addAssignment($assignments);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAssignment(\ZesharCRM\Bundle\GoalsBundle\Entity\GoalAssignment $assignments)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAssignment', array($assignments));

        return parent::removeAssignment($assignments);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignments', array());

        return parent::getAssignments();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoalCategory(\ZesharCRM\Bundle\CoreBundle\Entity\LeadCategory $goalCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoalCategory', array($goalCategory));

        return parent::setGoalCategory($goalCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoalCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoalCategory', array());

        return parent::getGoalCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotal($total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotal', array($total));

        return parent::setTotal($total);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotal', array());

        return parent::getTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartsAt($startsAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartsAt', array($startsAt));

        return parent::setStartsAt($startsAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartsAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartsAt', array());

        return parent::getStartsAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinishesAt($finishesAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinishesAt', array($finishesAt));

        return parent::setFinishesAt($finishesAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinishesAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinishesAt', array());

        return parent::getFinishesAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', array());

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
