<?php

namespace ZesharCRM\Bundle\LeadScoringBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LeadScoringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoringCriteriaRepository extends EntityRepository
{
}
