ZesharCRM\Bundle\CoreBundle\Entity\LeadType:
    type: entity
    table: lead_type
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255

    manyToOne:
        creator:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: leadTypes
            joinColumns:
                creator:
                    nullable: true
                    referencedColumnName: id
    lifecycleCallbacks: {  }
