ZesharCRM\Bundle\CoreBundle\Entity\LeadEventType:
    type: entity
    table: lead_event_type
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255

    manyToOne:
        creator:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: leadEventTypes
            joinColumns:
                creator:
                    nullable: true
                    referencedColumnName: id
    lifecycleCallbacks: {  }
