ZesharCRM\Bundle\CoreBundle\Entity\LeadPrequalificationAuto:
    type: entity
    table: lead_prequalification_auto
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        year:
            type: integer
            nullable: true
        make:
            type: string
            length: 255
            nullable: true
        model:
            type: string
            length: 255
            nullable: true
        vinNumber:
            type: string
            length: 255
            column: vin_number
            nullable: true
    manyToOne:
        lead:
            targetEntity: LeadSubject
            cascade: {  }
            mappedBy: null
            inversedBy: prequalificationAutos
            joinColumns:
                lead:
                    nullable: false
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
