ZesharCRM\Bundle\CoreBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: ZesharCRM\Bundle\CoreBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        widgetsData:
            type: text
            column: widgets_data
            nullable: true
        lspCode:
            type: string
            length: 255
            column: lsp_code
            nullable: true
        firstName:
          type: string
          length: 20
          column: first_name
          nullable: true
        lastName:
          type: string
          length: 20
          column: last_name
          nullable: true
        disabled:
          type: integer
          length: 5
          nullable: true
    oneToMany:
        assignedLeads:
            targetEntity: Lead
            cascade: {  }
            mappedBy: assignee
        createdLeads:
            targetEntity: Lead
            cascade: {  }
            mappedBy: creator
        assignedOpportunities:
            targetEntity: Opportunity
            cascade: {  }
            mappedBy: assignee
        createdOpportunities:
            targetEntity: Opportunity
            cascade: {  }
            mappedBy: creator
        assignedActivities:
            targetEntity: Activity
            cascade: {  }
            mappedBy: assignee
        createdActivities:
            targetEntity: Activity
            cascade: {  }
            mappedBy: creator
        performedOperations:
            targetEntity: Operation
            cascade: ["remove"]
            mappedBy: performer
        performedMilestoneOperations:
            targetEntity: MilestoneOperation
            cascade: ["remove"]
            mappedBy: performer
        performedActions:
            targetEntity: Log
            cascade: ["remove"]
            mappedBy: performer
        assignedCallReports:
            targetEntity: ZesharCRM\Bundle\CallsBundle\Entity\CallReporting
            cascade: {  }
            mappedBy: assignee
        leadCategories:
            targetEntity: LeadCategory
            mappedBy: creator
            cascade: ["persist", "remove"]
        leadEventTypes:
            targetEntity: LeadEventType
            mappedBy: creator
            cascade: ["persist", "remove"]
        leadSources:
            targetEntity: LeadSource
            mappedBy: creator
            cascade: ["persist", "remove"]
        leadTypes:
            targetEntity: LeadType
            mappedBy: creator
            cascade: ["persist", "remove"]
        payments:
            targetEntity: PaymentHistory
            mappedBy: creator
            cascade: ["persist", "remove"]
        creditCards:
            targetEntity: CreditCard
            mappedBy: owner
            cascade: ["persist", "remove"]
        billingInfo:
            targetEntity: BillingInfo
            mappedBy: creator
            cascade: ["persist", "remove"]

    manyToOne:
        company:
            targetEntity: Company
            cascade: { }
            mappedBy: null
            inversedBy: users
            joinColumns:
                company:
                    nullable: true
                    referencedColumnName: id

                