<?php

namespace ZesharCRM\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ZesharCRM\Bundle\CoreBundle\Entity\User;
use ZesharCRM\Bundle\CoreBundle\Entity\ExpiredActivity;
use ZesharCRM\Bundle\CoreBundle\Enum\ActivityStatus;

/**
 * ExpiredActivityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpiredActivityRepository extends EntityRepository
{

}

