ZesharCRM\Bundle\GoalsBundle\Entity\Goal:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: [goalCategory], message: 'Category must be unique!'}
    properties:
        title:
            - Length:
                min: 2
                max: 50
                minMessage: "Your first name must be at least {{ limit }} characters length"
                maxMessage: "Your first name cannot be longer than {{ limit }} characters length"
        description:
             - NotBlank: ~
        estimated:
            - Range:
                min: 1
                max: 100
                minMessage: "You must be at least {{ limit }} estimated to enter"
                maxMessage: "You cannot be estimated than {{ limit }} to enter"
ZesharCRM\Bundle\CoreBundle\Entity\Lead:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: { fields: [name,leadCategory,contactCard], message: 'Name, category and contact card must be unique!'}
    properties:
        contactCard:
            - NotBlank: ~
            - NotNull: ~