<?php

namespace ZesharCRM\Bundle\LeadsRegenerationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LeadsRegenerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadsRegenerationRepository extends EntityRepository
{
    public function findRegenerationLeads(){
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('v')
            ->from('ZesharCRMLeadsRegenerationBundle:LeadsRegeneration', 'v')
            ->andWhere( 'v.regenerationAt < :now')
            ->setParameters(array('now' => new \DateTime()));
        return $qb->getQuery()->getResult();
    }
}
