<?php

namespace ZesharCRM\Bundle\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ZesharCRM\Bundle\CoreBundle\Entity\Lead;
use ZesharCRM\Bundle\CoreBundle\Entity\LeadAttachment;
use \ZesharCRM\Bundle\CoreBundle\Entity\User;
use \ZesharCRM\Bundle\CoreBundle\Entity\Opportunity;
use ZesharCRM\Bundle\CoreBundle\Entity\OpportunityAttachment;
use ZesharCRM\Bundle\CoreBundle\Enum\DealStatus;
use ZesharCRM\Bundle\CoreBundle\Enum\OpportunityStatus;
use ZesharCRM\Bundle\CoreBundle\Enum\LeadType;

/**
 * LeadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadRepository extends EntityRepository
{
    
    /**
     * Close a lead with SUCCESS status and create new opportunity from it
     * @return \ZesharCRM\Bundle\CoreBundle\Entity\Opportunity
     * @throws \BadMethodCallException When the lead was already in SUCCESS state
     */
    public function createOpportunity(Lead $lead)
    {
        if (DealStatus::SUCCESS === $lead->getStatus()) {
            throw new \BadMethodCallException('This lead was already closed as success.');
        }

        $em = $this->getEntityManager();

        $lead->setStatus(DealStatus::SUCCESS);
        $lead->setIsArchive(true);

        if (LeadType::COLD === $lead->getType()) {
            $lead->setType(LeadType::WARM);
        }

        $opportunity = new Opportunity();
        
        // copy all fields
        $opportunity
            ->setLead($lead)
            ->setName($lead->getName())
            ->setStatus(OpportunityStatus::PENDING_OPPORTUNITY)
            ->setCreator($lead->getCreator())
            ->setAssignee($lead->getAssignee())
            ->setContactCard($lead->getContactCard())
            ->setOpportunityCategory($lead->getLeadCategory())
            ->setPurchaseAmount($lead->getPurchaseAmount())
            ->setPurchasedAt($lead->getPurchasedAt())
            ->setEstimatedValue($lead->getEstimatedValue())
        ;

        foreach ($lead->getPrequalificationAutos() as $auto) {
            $opportunity->addPrequalificationAuto($auto);
        }

        foreach ($lead->getPrequalificationDrivers() as $driver) {
            $opportunity->addPrequalificationDriver($driver);
        }

        foreach ($lead->getPrequalificationInsuredAddresses() as $insuredDriver) {
            $opportunity->addPrequalificationInsuredAddress($insuredDriver);
        }

        /** @var $leadAttachment LeadAttachment */
        foreach ($lead->getAttachments() as $leadAttachment) {
            $opportunityAttachment = new OpportunityAttachment();
            $opportunityAttachment
                ->setAttachment($leadAttachment->getAttachment())
                ->setOpportunity($opportunity)
            ;
            $opportunity->addAttachment($opportunityAttachment);
        }
        
        $em->persist($opportunity);
        $em->flush($lead);
        
        return $opportunity;
    }
    
    /**
     * Assigns a lead to a user
     * @param \ZesharCRM\Bundle\CoreBundle\Entity\Lead $lead
     * @param \ZesharCRM\Bundle\CoreBundle\Entity\User $assignee
     */
    public function assignLead(Lead $lead, User $assignee)
    {
        $em = $this->getEntityManager();
        $lead->setAssignee($assignee);
        $em->flush($lead);
    }
    
    /**
     * Switch a lead into CANCELLED status
     * @param \ZesharCRM\Bundle\CoreBundle\Entity\Lead $lead
     * @throws \BadMethodCallException When the lead was already in CANCELLED state
     */
    public function cancelLead(Lead $lead)
    {
        if (DealStatus::CANCELLED === $lead->getStatus()) {
            throw new \BadMethodCallException('This lead is already cancelled.');
        }
        
        $em = $this->getEntityManager();
        $lead->setStatus(DealStatus::CANCELLED);
        $em->flush($lead);
    }
    
    /**
     * Switch a lead into PENDING status
     * @param \ZesharCRM\Bundle\CoreBundle\Entity\Lead $lead
     * @throws \BadMethodCallException When the lead was already in PENDING state
     */
    public function reopenLead(Lead $lead)
    {
        if (DealStatus::PENDING === $lead->getStatus()) {
            throw new \BadMethodCallException('This lead is already open.');
        }
        
        $em = $this->getEntityManager();
        $lead->setStatus(DealStatus::PENDING);
        $em->flush($lead);
    }


    /**
     * Switch a lead into WARM type
     * @param \ZesharCRM\Bundle\CoreBundle\Entity\Lead $lead
     * @throws \BadMethodCallException
     */
    public function warmupLead(Lead $lead) {
        if (LeadType::WARM === $lead->getType()) {
            throw new \BadMethodCallException('This lead is already warm.');
        }
        if (DealStatus::PENDING !== $lead->getStatus()) {
            throw new \BadMethodCallException('This lead is closed.');
        }
        
        $em = $this->getEntityManager();
        $lead->setType(LeadType::WARM);
        $em->flush($lead);
    }

    public function createLead($contactCard, $product, $user)
    {
        $em = $this->getEntityManager();

        $lead = new Lead();

        $lead
            ->setName('X-Sell '.$product->getTitle())
            ->setStatus(DealStatus::PENDING)
            ->setType(LeadType::COLD)
            ->setCreator($user)
            ->setAssignee($user)
            ->setContactCard($contactCard)
            ->setLeadCategory($product)
        ;

        $em->persist($lead);

        $em->flush();

        return $lead;
    }
    
    public function fetchLeadsByAssignee(User $assignee, $count = 5)
    {
        $leads = $this->findBy(array('assignee' => $assignee->getId(), 'status' => DealStatus::PENDING), array('updatedAt' => 'DESC'), $count);
        return $leads;
    }
    
}
