<?php

namespace ZesharCRM\Bundle\CallsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CallsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallReportingRepository extends EntityRepository
{
}
